[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Automatische Installation der benötigten Bibliotheken
lib_deps =
    miguelbalboa/MFRC522 @ ^1.4.11
    thijse/ArduinoLog @ ^1.1.1