; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; OTA credentials are defined only in include/secret.h
[env]
lib_compat_mode = strict
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Shared dependencies for all configurations
lib_deps = 
	miguelbalboa/MFRC522 @ ^1.4.11
	thijse/ArduinoLog @ ^1.1.1
	ayushsharma82/ElegantOTA@^3.1.7


[env:esp32dev-usb]
upload_protocol = esptool


[env:esp32dev-ota]
upload_protocol = custom
upload_port = 192.168.1.17
extra_scripts = platformio_upload.py
custom_upload_url = http://192.168.1.17/update


