[platformio]
default_envs = sammelplatine_usb
extra_configs = platformio.secrets.ini

[env]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit MPL3115A2 Library @ ^1.2.4
    adafruit/Adafruit MCP9808 Library @ ^2.0.0
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    bblanchon/ArduinoJson @ ^7.0.0

build_flags =
    -DSERVER_HOST=\"${secrets.server_host}\"
    -DSERVICE_TOKEN=\"${secrets.service_token}\"

[env:sammelplatine_usb]
; Erstflash per USB/Serial
