[platformio]
default_envs = lasersaur_hmi_usb
extra_configs = platformio.secrets.ini

[env]
platform = arduino_mbed
board = arduino_giga_r1
framework = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/adafruit/Adafruit_MPL3115A2_Library.git
    https://github.com/adafruit/Adafruit_MCP9808_Library.git
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    bblanchon/ArduinoJson @ ^7.0.0

build_flags =
    -DSERVER_HOST=\"${secrets.server_host}\"
    -DSERVICE_TOKEN=\"${secrets.service_token}\"
    -DWIFI_SSID=\"${secrets.wifi_ssid}\"
    -DWIFI_PASSWORD=\"${secrets.wifi_password}\"

[env:lasersaur_hmi_usb]
; Erstflash per USB/Serial

[env:lasersaur_hmi_ota]
upload_protocol = ota
upload_port = lasersaur-hmi.local
