name: PlatformIO Build RFIDBOX_PoC

on:
  push:
    branches:
      - main
    paths:
      - 'firmware/projects/RFIDBOX_PoC/**'
      - '.github/workflows/build.yml'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
    paths:
      - 'firmware/projects/RFIDBOX_PoC/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PlatformIO
        run: pip install --upgrade platformio

      - name: Reconstruct secret.h
        env:
          SECRET_DATA: ${{ secrets.MY_SECRET_3D_Printer_H }}
        run: |
          mkdir -p firmware/projects/RFIDBOX_PoC/include
          cat <<EOF > firmware/projects/RFIDBOX_PoC/include/secret.h
          $SECRET_DATA
          EOF

      - name: Run PlatformIO Build
        run: pio run -d firmware/projects/RFIDBOX_PoC

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: firmware/projects/RFIDBOX_PoC/.pio/build/esp32dev/firmware.bin
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}